-- CREATE DATA BASE FOR COMPANY
DROP DATABASE IF EXISTS company_db;
CREATE DATABASE company_db;

USE company_db;

-- CREATE TABLE FOR DEPARTMENTS
CREATE TABLE departments (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL
);

-- CREATE TABLE FOR ROLES
CREATE TABLE roles (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(30) NOT NULL,
    salary DECIMAL(6,2) NOT NULL,
    department_id INT,
    FOREIGN KEY (department_id)
    REFERENCES departments(id)
    ON DELETE SET NULL
);

