-- DATA FOR DEPARTMENTS
INSERT INTO departments (name)
VALUES ("Sales"),
        ("Safety"),
        ("Operations"),
        ("Payroll"),
        ("Shop");

-- DATA FOR roles
INSERT INTO roles (title, salary, department_id)
VALUES ("Director of Sales", 200000, 1),
        ("Sales Manager", 150000, 1),
        ("Sales Representative", 100000, 1),
        ("Director of Safety", 100000, 2),
        ("Safety Manager", 75000, 2),
        ("Safety Representative", 50000, 2),
        ("Director of Operations", 200000, 3),
        ("Customer Service Manager", 125000, 3),
        ("Fleet Operations Manager", 125000, 3),
        ("Customer Service Lead", 90000, 3),
        ("Fleet Operations Lead", 90000, 3),
        ("Customer Service Representative", 65000, 3),
        ("Driver Manager", 55000, 3),
        ("Director of Payroll", 95000, 4),
        ("Payroll Manager", 70000, 4),
        ("Payroll Representative", 45000, 4),
        ("Director of Maintenance", 100000, 5),
        ("Shop Manager", 75000, 5),
        ("Mechanic", 55000, 5);

-- DATA FOR EMPLOYEES
-- NOTE, NAMES WERE RANDOMLY GENERATED THROUGH A RANDOM NAME GENERATOR
-- https://www.randomlists.com/random-names?qty=60
INSERT INTO employees (first_name, last_name, role_id, manager_id)
VALUES ("Danny", "Cobb", 1, NULL),
        ("Jackson", "Galloway", 2, 1),
        ("Gary", "Jimenez", 3, 2),
        ("Ashley", "Ross", 3, 2),
        ("Raul", "McKenzie", 3, 2),
        ("Rod", "Shepherd", 3, 2),
        ("Alisson", "Jones", 4, NULL),
        ("Kameron", "Rosario", 5, 4),
        ("Kenneth", "Ford", 6, 5),
        ("Bob", "Bernard", 6, 5),
        ("London", "Bentley", 6, 5),
        ("Morgan", "Dickson", 6, 5),
        ("Alden", "Hahn", 6, 5),
        ("Troy", "Hamilton", 7, NULL),
        ("Shea", "Rojas", 8, 7),
        ("Mariah", "Roberts", 9, 7),
        ("Angel", "Mata", 10, 8),
        ("Lena", "McFarland", 11, 9),
        ("Heather", "Vang", 12, 10),
        ("Lamar", "Andrews", 12, 10),
        ("Gideon", "Day", 12, 10),
        ("Keely", "Koch", 12, 10),
        ("Anahi", "Curtis", 12, 10),
        ("Jayda", "Stephens", 12, 10),
        ("Lea", "Barnett", 13, 11),
        ("Miah", "Ali", 13, 11),
        ("Kayley", "Melton", 13, 11),
        ("Sam", "Ross", 13, 11),
        ("Haylie", "Peters", 13, 11),
        ("Ana", "Brady", 13, 11),
        ("Israel", "Joyce", 13, 11),
        ("Angelique", "Banks", 13, 11),
        ("Rylee", "Hayes", 14, NULL),
        ("Kimora", "Oneili", 15, 14),
        ("Valentina", "Donovan", 16, 15),
        ("Emerson", "Clark", 16, 15),
        ("Sabrina", "Hampton", 16, 15),
        ("Giancarlo", "Norton", 16, 15),
        ("Tony", "Chung", 17, NULL),
        ("Toby", "Koch", 18, 17),
        ("Heath", "Stone", 19, 18),
        ("Lucian", "Avery", 19, 18),
        ("Laney", "Choi", 19, 18),
        ("Zack", "Taylor", 19, 18),
        ("Colin", "Massey", 19, 18),
        ("Jasmin", "Vance", 19, 18);